Algoritmo "quadrados entre 15 e 200"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2021
Var
// Seção de Declarações das variáveis 
   a:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   a<-15
   repita
         escreval(a*a)
         a<-a+1
   ate a=201
         

Fimalgoritmo