Algoritmo "quadrados de 15 a 200"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/03/2021
Var
// Seção de Declarações das variáveis 
   b:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para b:=15 ate 200 faca
        escreval(b*b)
   fimpara
        

Fimalgoritmo