Algoritmo "matriz C soma de M e N"
// Disciplina   : ALGORITMO ESTRUTURADO
// Professor   : RONILSON RODRIGUES PINHO 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/05/2021
Var
// Seção de Declarações das variáveis 
   a: vetor[1..4,1..6] de inteiro
   b: vetor[1..6,1..4] de inteiro
   

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo